import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../public/_worker.js';
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aKa8AAAAASUVORK5CYII=';
function req(prompt='Işığı düzelt',bytes=Buffer.from(png,'base64')){const form=new FormData();form.append('image',new Blob([bytes],{type:'image/png'}),'input.png');form.append('prompt',prompt);form.append('subject',JSON.stringify({x:25,y:40}));return new Request('https://photo.example/api/edit',{method:'POST',headers:{Origin:'https://photo.example'},body:form})}
test('page and unconfigured connection are honest',async()=>{const page=await worker.fetch(new Request('https://photo.example/'));assert.equal(page.status,200);assert.match(await page.text(),/Yapay zekâ ile düzenle/);const status=await worker.fetch(new Request('https://photo.example/api/status'));assert.equal((await status.json()).ready,false);const res=await worker.fetch(req());assert.equal(res.status,503);assert.equal((await res.json()).error.code,'AI_NOT_CONFIGURED')});
test('blocks foreign origin and invalid image before any model call',async()=>{const env={OPENAI_API_KEY:'test-not-a-secret'};const bad=new Request('https://photo.example/api/edit',{method:'POST',headers:{Origin:'https://other.example'}});assert.equal((await worker.fetch(bad,env)).status,403);assert.equal((await worker.fetch(req('Işığı düzelt',Buffer.from('not an image')),env)).status,400);assert.equal((await worker.fetch(req(''),env)).status,400)});
test('sends image and user request to image editing API, returns PNG',async()=>{const original=globalThis.fetch;let called=0;globalThis.fetch=async(url,options)=>{called++;assert.equal(url,'https://api.openai.com/v1/images/edits');assert.equal(options.headers.Authorization,'Bearer example-key');assert.equal(options.body.get('model'),'gpt-image-2.5-sunburst');assert.match(options.body.get('prompt'),/Işığı düzelt/);assert.match(options.body.get('prompt'),/25.0%/);assert.equal(options.body.get('image').type,'image/png');return Response.json({data:[{b64_json:png}]})};try{const res=await worker.fetch(req(),{OPENAI_API_KEY:'example-key'});assert.equal(res.status,200);assert.equal(res.headers.get('Content-Type'),'image/png');assert.deepEqual(Buffer.from(await res.arrayBuffer()),Buffer.from(png,'base64'));assert.equal(called,1)}finally{globalThis.fetch=original}});
test('provider errors are readable without exposing provider payloads',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({error:{message:'sensitive provider diagnostic'}},{status:401});try{const res=await worker.fetch(req(),{OPENAI_API_KEY:'example-key'});assert.equal(res.status,503);const body=await res.text();assert.match(body,/AI_ACCESS/);assert.doesNotMatch(body,/sensitive|example-key/)}finally{globalThis.fetch=original}});
