const MAX_BYTES=12*1024*1024;
const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...headers,'Content-Type':'application/json; charset=utf-8'}})}
function problem(code,message,status){return json({error:{code,message}},status)}
async function limitedBody(request){const reader=request.body?.getReader();if(!reader)throw new Error('empty');let size=0,parts=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>MAX_BYTES){await reader.cancel();throw new Error('large')}parts.push(value)}return new Blob(parts)}
export default {async fetch(request,env={}){
const url=new URL(request.url);
if(url.pathname==='/api/status'&&request.method==='GET')return json({ready:Boolean(env.OPENAI_API_KEY?.trim()),message:env.OPENAI_API_KEY?.trim()?'Yapay zekâ bağlantısı yapılandırıldı.':'Otomatik düzenleme bağlantısı henüz etkin değil.'});
if(url.pathname==='/api/edit'){
if(request.method!=='POST')return problem('METHOD','Bu işlem desteklenmiyor.',405);
const origin=request.headers.get('Origin');if(origin&&origin!==url.origin)return problem('ORIGIN','İsteği uygulama üzerinden gönderin.',403);
if(!env.OPENAI_API_KEY?.trim())return problem('AI_NOT_CONFIGURED','Otomatik düzenleme bağlantısı henüz etkin değil. Fotoğrafınız gönderilmedi.',503);
if(!request.headers.get('Content-Type')?.startsWith('multipart/form-data'))return problem('TYPE','Fotoğraf ve düzenleme isteği gerekli.',415);
let data;try{const blob=await limitedBody(request);data=await new Response(blob,{headers:{'Content-Type':request.headers.get('Content-Type')}}).formData()}catch(e){return problem('UPLOAD',e.message==='large'?'Fotoğraf en fazla 10 MB olabilir.':'Fotoğraf okunamadı.',400)}
const image=data.get('image'),prompt=data.get('prompt');if(!(image instanceof Blob)||image.size===0||image.size>10*1024*1024)return problem('IMAGE','En fazla 10 MB bir fotoğraf seçin.',400);
if(!['image/jpeg','image/png','image/webp'].includes(image.type))return problem('IMAGE_TYPE','JPG, PNG veya WebP fotoğraf seçin.',400);
if(typeof prompt!=='string'||prompt.trim().length<3||prompt.length>3000)return problem('PROMPT','3–3000 karakterlik bir düzenleme isteği yazın.',400);
const bytes=new Uint8Array(await image.slice(0,12).arrayBuffer());const isPng=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71;const isJpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const isWebp=String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';if(!isPng&&!isJpg&&!isWebp)return problem('INVALID_IMAGE','Dosya geçerli bir fotoğraf değil.',400);
const target=data.get('subject');let targetText='';if(typeof target==='string'&&target){try{const p=JSON.parse(target);if(Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=0&&p.x<=100&&p.y>=0&&p.y<=100)targetText=` The user marked the subject to preserve at ${p.x.toFixed(1)}% from the left and ${p.y.toFixed(1)}% from the top of the supplied image. Preserve this subject.`}catch{}}
const fidelity=data.get('preserve')!=='false'?' Preserve the identity, facial features, skin tone and age of retained people. Avoid beauty filters and changes to faces.':'';
const instruction='Edit the supplied photograph according to the user request below. Return an edited photograph. Preserve the original composition and all unrelated objects unless the user requests changes. Reconstruct removed areas naturally with coherent lighting and texture. Do not add watermarks or captions.'+fidelity+targetText+'\nUser request: '+prompt.trim();
const body=new FormData();body.append('image',image,'photo.'+({ 'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[image.type]));body.append('prompt',instruction);body.append('model',env.OPENAI_IMAGE_MODEL||'gpt-image-2.5-sunburst');body.append('quality','high');body.append('size','auto');body.append('output_format','png');body.append('n','1');
try{const result=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:'Bearer '+env.OPENAI_API_KEY},body,signal:AbortSignal.timeout(180000)});const payload=await result.json();if(!result.ok){const code=payload.error?.code;if(code==='moderation_blocked'||code==='content_policy_violation')return problem('REQUEST_BLOCKED','Bu fotoğraf veya istek işlenemedi. İsteğinizi değiştirip yeniden deneyin.',422);if(result.status===401||result.status===403)return problem('AI_ACCESS','Yapay zekâ bağlantısının erişimi doğrulanamadı. Uygulama sahibi bağlantıyı kontrol etmeli.',503);if(result.status===429)return problem('AI_BUSY','Yapay zekâ hizmetinin kullanım sınırına ulaşıldı. Daha sonra yeniden deneyin.',429);return problem('AI_ERROR','Fotoğraf düzenlenemedi. Biraz sonra tekrar deneyin.',502)}const encoded=payload.data?.[0]?.b64_json;if(!encoded)return problem('NO_IMAGE','Düzenlenmiş fotoğraf alınamadı.',502);const decoded=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0));return new Response(decoded,{headers:{...headers,'Content-Type':'image/png','Content-Disposition':'inline; filename="duzenlenmis.png"'}})}catch(e){return problem('CONNECTION',e.name==='TimeoutError'?'İşlem beklenenden uzun sürdü. Tekrar denemeden önce biraz bekleyin.':'Yapay zekâ hizmetine ulaşılamadı. Daha sonra yeniden deneyin.',504)}
}
if((url.pathname==='/'||url.pathname==='/index.html')&&request.method==='GET')return new Response(HTML,{headers:{...headers,'Content-Type':'text/html; charset=utf-8','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'self'"}});
return new Response('Bulunamadı',{status:404,headers});
}};
